### ISSUE TITLE
NaN support for floats

### ISSUE THREAD

**Issue by p-avital** [pheki/rudano#1]
Probably the dumbest lack in JSON, `NaN` is not supported, requiring ugly hacks such as using `null` instead.

I haven't seen it in the crate's readme, so forgive me if I'm raising concern over nothing, but I think NaN should be encodable as part of the float type, just like it is with the ISO binary representation.

As much as I like your plan for rudano, JSON's wider support (and legibility for my non rustacean colleagues) still has me sitting on the fence about using it any time soon. But first class support for NaN is a rare but previous thing to me, so that might just convince me to swap ;p

Also, any plans on making rudano available for other platforms ?

**Comment by pheki** [comment]
Yes, lack of NaN and ±infinity in JSON is really disappointing and has bitten me in the past. This crate actually supports NaN as exactly this identifier: `NaN`, based on how [rustc prints it](https://play.rust-lang.org/). I should at least add this to the "Differences" section of the readme, as this is not how you create NaN in rust. Also, there are [tests for these edge cases](https://github.com/pheki/rudano/blob/867dab87faff2a31e0e80e7af196a59aa60c880c/src/de.rs#L1651) in the crate, so you could also check there.

On the other side, maybe [JSON5](https://json5.org/) suits your needs? I believe that's best on the interoperability and familiarity side of things. Rudano may be better for configuration/state files and Rust-based projects.

> Also, any plans on making rudano available for other platforms?

I don't want to maintain full libraries (parser, etc) in other languages, but I'm considering adding bindings for e.g. python. That would require me some effort though to make it ergonomic. What platforms are you interested in?

**Comment by p-avital** [comment]
> I'm considering adding bindings for e.g. python. That would require me some effort though to make it ergonomic. What platforms are you interested in?

Honestly, I like rudano, it's just more full featured than JSON, so it'd be nice if it could take it over at some point. But for that, it'd need to be available across platforms, and also for more people than just me to find the idea appealing.

I'm honestly too busy (busy might not be the word, I have a PhD that I need to stop neglecting in favour of projects like yours) to assist for now, but I guess bindings for a few major languages would help. Python and JS mostly (maybe WASM can help with the latter).

I didn't known about JSON5, thanks for pointing it out, I'll probably give it a try :)

**Comment by pheki** [comment]
Hmmm yes, wasm may make it simple to add JS bindings, but first I'd have to add `rudano::Value` and add proper testing to `deserialize_any` (deserialization without knowing the target type).

I'll close this issue as I've documented `NaN` and `+-inf` in the README.md, but I may add bindings to other languages in the future, in case I find time it ;)

Good luck on your PhD
